group: deprecated-2017Q3
language: julia
julia:
  - 1.0
os:
  - linux
  - osx
env:
  - GROUP=Test
matrix:
    fast_finish: true
    allow_failures:
       - env: GROUP=Test
         os: osx

notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg;Pkg.update();
             Pkg.clone(pwd(), "Turing");
             Pkg.build("Turing");
             if ENV["GROUP"] == "Test"
                Pkg.test("Turing"; coverage=true)
             else
                println("Unknown test command.")
             end'
after_success:
  - julia -e 'if ENV["GROUP"] == "Test"
                using Pkg; cd(Pkg.dir("Turing")); Pkg.add("Coverage");
                using Coverage; Coveralls.submit(process_folder())
              end'
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg, Turing;
              cd(joinpath(dirname(pathof(Turing)), ".."));
              include(joinpath("docs", "make.jl"))'
notifications:
    email: false
